museu_matematica/museu_matematica/urls.py
from django.contrib import admin
from django.urls import path
from museu_matematica.views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.urls.base import reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('exposicoes/', ExposicaoListView.as_view(), name='exposicoes'),
    path('adicionar-exposicao/', ExposicaoCreate.as_view(), name='exposicao-create'),
    path('deletar-exposicao/<int:pk>', ExposicaoDelete.as_view(), name='exposicao-delete'),
    path('editar-exposicao/<int:pk>', ExposicaoUpdate.as_view(), name='exposicao-editar'),
    path('reservar/<int:pk>', ReservaCreateView.as_view(), name='reservar'),
    path('lista-reservas/', ReservaListView.as_view(), name="lista-reservas"),
    path('editar-reserva/<int:pk>', ReservaUpdate.as_view(), name="reserva-editar"),
    path('reserva-delete/<int:pk>', ReservaDelete.as_view(), name="reserva-delete"),
    path('accounts/login/', LoginView.as_view(template_name="museu_matematica/login.html"), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page = reverse_lazy('homepage')), name='logout'),
    path('accounts/registro/', registro, name = 'registro'),
    path("reserva-ajax", verificaReserva, name = 'reserva-ajax'),
]

app_name = 'museu_matematica'

museu_matematica/museu_matematica/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Modelo para reservarexposicoes

class Exposicao(models.Model):
    titulo = models.CharField(max_length=300)
    descricao = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.titulo)

class Reserva(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True, blank = True)
    exposicao = models.ForeignKey(Exposicao, on_delete = models.CASCADE, null = True, blank = True)
    dataEntrada = models.DateField(verbose_name = 'Data de entrada', help_text = 'Utilize o formato AAAA-MM-DD')
    dataSaida =  models.DateField(verbose_name = 'Data de saída', help_text = 'Utilize o formato AAAA-MM-DD')
    horarioEntrada = models.TimeField(verbose_name = 'Horário de entrada', help_text = 'Utilize o formato HH:MM')
    horarioSaida = models.TimeField(verbose_name = 'Horário de saída', help_text = 'Utilize o formato HH:MM')

    def __str__(self):
        return str(self.user) + ' - ' + str(self.exposicao) + ' - ' + str(self.dataEntrada)

museu_matematica/museu_matematica/forms.py
from django.db.models import fields
from django import forms
from museu_matematica.models import *

class ExposicaoModel2Form(forms.ModelForm):
    class Meta:
        model = Exposicao
        fields = '__all__'

class ReservaModel2Form(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = '__all__'

class ReservaModel2FormCreate(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['dataEntrada', 'dataSaida', 'horarioEntrada', 'horarioSaida']

museu_matematica/museu_matematica/views.py
from django.shortcuts import render
from django.forms.forms import Form
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.models import User

from museu_matematica.models import Reserva, Exposicao
from museu_matematica.forms import ExposicaoModel2Form
from museu_matematica.forms import ReservaModel2FormCreate

from django.http.response import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

class ExposicaoListView(View):
    def get(self, request, *args, **kwargs):
        exposicoes = Exposicao.objects.all()
        context = { 'exposicoes': exposicoes, }
        return render(request, 'museu_matematica/exposicoes.html', context)

class ExposicaoCreate(View):
    def get(self, request, *args, **kwargs):
        context = {
            'form': ExposicaoModel2Form, 
            }
        return render(request, 'museu_matematica/exposicao-adicionar.html', context)

    def post(self, request, *args, **kwargs):
        form = ExposicaoModel2Form(request.POST)
        if form.is_valid():
            exposicao = form.save()
            exposicao.save()
            return HttpResponseRedirect(reverse_lazy("exposicoes"))

class ExposicaoDelete(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        exposicao = Exposicao.objects.get(pk=pk)
        context = { 'exposicao': exposicao }
        return render(request, 'museu_matematica/exposicao-delete.html', context)

    def post(self, request, pk, *args, **kwargs):
        Exposicao.objects.filter(pk=pk).delete()
        return HttpResponseRedirect(reverse_lazy("exposicoes"))

class ExposicaoUpdate(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs): # Busca os dados de uma exposicao e exibe como um formulário
        exposicao = Exposicao.objects.get(pk=pk)
        formulario = ExposicaoModel2Form(instance=exposicao)
        context = {'form': formulario, 'exposicao': exposicao } # Coloca o registro recuperado do banco e coloca num formulário
        return render(request, 'museu_matematica/exposicao-editar.html', context)

    def post(self, request, pk, *args, **kwargs): # Recebe os dados de uma exposicao e atualiza o banco de dados
        exposicao = get_object_or_404(Exposicao, pk=pk) # Pega a exposicao ou retorna erro 404
        formulario = ExposicaoModel2Form(request.POST, instance=exposicao)
        if formulario.is_valid() and self.request.user.is_superuser:
            contato = formulario.save()
            contato.save()
            return HttpResponseRedirect(reverse_lazy("exposicoes"))
        else:
            context = {'form': formulario, 'exposicao': exposicao}
            return render(request,'museu_matematica/exposicao-editar.html', context)

def verificaReserva(request):
    search_input_hrEntrada = request.GET.get('hrEntrada')
    search_input_hrSaida = request.GET.get('hrSaida')
    search_input_dtEntrada = request.GET.get('dtEntrada')
    search_input_dtSaida = request.GET.get('dtSaida')
    
    print(request)

    if(search_input_hrEntrada == search_input_hrSaida and search_input_dtEntrada == search_input_dtSaida and search_input_hrEntrada != ""):
        resposta = {
                'hrIgual':
                    'True'}
        return JsonResponse(resposta)
    else:
        resposta = {
                'hrIgual':
                    'False'}
        return JsonResponse(resposta)


class ReservaListView(LoginRequiredMixin, ListView):
    model = Reserva
    template_name = 'museu_matematica/lista-reservas.html'
    context_object_name = 'reservas'
    success_url = reverse_lazy("lista-reservas")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.request.user.is_superuser:
            context['reservas'] = context['reservas'].filter(user = self.request.user) # Apenas os itens do usuário logado (se for admin, vê todos)

        search_input = self.request.GET.get('search-area') or ''

        if search_input:
            context['reservas'] = context['reservas'].filter(dataEntrada__exact=search_input)

        context['search_input'] = search_input
        print(context)
        

        return context
        

class ReservaDetail(LoginRequiredMixin, CreateView):
    def get(self, request, pk, *args, **kwargs):
        reserva = Reserva.objects.get(pk=pk)
        context = { 'reserva': reserva }
        return render(request, 'museu_matematica/reserva_detalhes.html', context)

    def post(self, request, *args, **kwargs):
        pass

class ReservaCreateView(View):
    def get(self, request, pk, *args, **kwargs):
        context = {
            'exposicao': Exposicao.objects.get(pk=pk),
            'formulario': ReservaModel2FormCreate, 
            }
        return render(request, "museu_matematica/reserva_exposicao.html", context) 
    def post(self, request, pk, *args, **kwargs):
        formulario = ReservaModel2FormCreate(request.POST)
        if formulario.is_valid():
            reserva = formulario.save()
            reserva.user = self.request.user
            reserva.exposicao = get_object_or_404(Exposicao, pk=pk)
            reserva.save()
            return HttpResponseRedirect(reverse_lazy("homepage"))

class ReservaCreate(LoginRequiredMixin, CreateView):
    model = Reserva
    template_name = 'museu_matematica/reserva_criar.html'
    context_object_name = 'reserva'
    fields = ['dataEntrada', 'dataSaida', 'horarioEntrada', 'horarioSaida']
    success_url = reverse_lazy("museu_matematica/reservas-exibe") # Após post submetido

    def form_valid(self, form, exposicao):
        form.instance.user = self.request.user
        form.instance.exposicao = Exposicao.objects.get(pk = exposicao)
        return super(ReservaCreate, self).form_valid(form)

        
class ReservaUpdate(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs): # Busca os dados de uma reserva e exibe como um formulário
        reserva = Reserva.objects.get(pk=pk)
        formulario = ReservaModel2FormCreate(instance=reserva)
        context = {'form': formulario, 'reserva': reserva} # Coloca o registro recuperado do banco e coloca num formulário
        return render(request, 'museu_matematica/reserva-editar.html', context)

    def post(self, request, pk, *args, **kwargs): # Recebe os dados de uma reserva e atualiza o banco de dados
        reserva = get_object_or_404(Reserva, pk=pk) # Pega a reserva ou retorna erro 404
        formulario = ReservaModel2FormCreate(request.POST, instance=reserva)
        if formulario.is_valid():
            contato = formulario.save()
            contato.save()
            return HttpResponseRedirect(reverse_lazy("lista-reservas"))
        # else:
            # context = {'formulario': formulario, } # Coloca o registro recuperado e coloca num formulário
            # return render(request, 'museu_matematica/reserva_criar.html', context)
            

class ReservaDelete(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        reserva = Reserva.objects.get(pk=pk)
        context = { 'reserva': reserva }
        return render(request, 'museu_matematica/reserva-delete.html', context)

    def post(self, request, pk, *args, **kwargs):
        reserva = Reserva.objects.filter(pk=pk).delete()
        return HttpResponseRedirect(reverse_lazy("lista-reservas"))

# Create your views here.
def homepage(request):
    return render(request, 'museu_matematica/index.html')

def login(request):
    return render(request, 'museu_matematica/login.html')

def reservar(request):
    return render(request, 'museu_matematica/reserva_exposicao.html')

def registro(request):
    if request.method == 'POST':
        # create user
        formulario = UserCreationForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('homepage')
        else:
            context = {'form': formulario, }
        return render(request, 'museu_matematica/registro.html', context)
    else:
        # render form
        formulario = UserCreationForm()
    context = {'form': formulario, }
    return render(request, 'museu_matematica/registro.html')

museu_matematica/museu_matematica/templates/museu_matematica/exposicao-adicionar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar exposição</title>
    <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    </head>
    <body>

        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <div class="form-wrapper">
            <h3>Adicionar nova exposição</h3>
            <form action="" method="POST">
                <fieldset style="width: max-content;">
                    {% csrf_token %}
                    <table class='formulario'>
                        {{ form.as_table }}
                    </table>
                    <button type="submit">Criar!</button>
                </fieldset>
        </div>
    </body>
    </form>

museu_matematica/museu_matematica/templates/museu_matematica/exposicao-delete.html
{% load static %}   
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Excluir exposição</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
        </head>
    <body>

        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <div class="form-wrapper">
            <form method="post">
                {% csrf_token %}
                <h3>Quer realmente remover a exposição {{ exposicao.titulo }}?</h3>
                <input class="delete-button" type="submit" value="Excluir">
            </form>
        </div>
    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/exposicao-editar.html
{% load static %}   
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Editar Exposição</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
        </head>
    <body>
        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}
        <div class="form-wrapper">
            <h3>Editar exposição "{{exposicao.titulo}}"</h3>
            <form action="" method="POST">
                <fieldset style="width: max-content;">
                    {% csrf_token %}
                    <table class='formulario'>
                        {{ form.as_table }}
                    </table>
                    <button type="submit">Reservar!</button>
                </fieldset>
            </form>
        </div>
    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/exposicoes.html
{% load static %}
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Exposições</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    </head>

    <body>
        
        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <div class ="hellotext_wrapper">
            <h3 class="hellotext">Olá, {% firstof user.username "visitante" %}!</h3>
            <h1 class="exposicoes_text">Exposições</h1>
            {% if request.user.is_superuser %}
            <a href="{% url 'exposicao-create' %}"><i class="material-icons" style="font-size:50px">+</i></a>         
        {% endif %}
        </div>

        <div class="exp_container">
            {% for exposicao in exposicoes %}
            <div class="exp_card">
                <img src="{% static 'museu-matematica/images/exposicao.jpg' %}">
                <p class="exp_card_title">{{exposicao.titulo}}</p>
                <p>{{exposicao.descricao}}</p>
                <div class="exp_buttons">
                    <!--se usuário não está autenticado-->
                    {% if not request.user.is_authenticated %}
                        <h4>Faça login para reservar</h4>
                    {% else %}
                        {% if request.user.is_superuser %}
                            <form action="{% url 'exposicao-editar' pk=exposicao.id %}">
                                <input type="submit" value="Editar" />
                            </form>
                            <form action="{% url 'exposicao-delete' pk=exposicao.id %}">
                                <input type="submit" value="Excluir" />
                            </form>
                        {% else %}
                        <form action="{% url 'reservar' pk=exposicao.id %}">
                            <input type="submit" value="Reservar" />
                        </form>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            {% empty %}
            <h3>Nenhuma exposição cadastrada, volte mais tarde!</h3>
            {% endfor %}
        </div>

    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/header.html
{% load static %}
<!--
Para incluir esse fragmento de página HTML
em uma página HTML use:
{ % include 'museu_matematica/header.html' % }
-->

<header class="header">
    <img src="{% static 'museu-matematica/images/logo.png' %}">
    <div class="menu">
        <a href="/">Sobre</a>
        <a href='{% url "exposicoes" %}'>Exposições</a>
        <a href='{% url "lista-reservas" %}'>Reservas</a>
        <a>Contato</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</header>

museu_matematica/museu_matematica/templates/museu_matematica/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Museu da Matemática do Rio de Janeiro</title>
    <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>
    <div class="structure">

        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <section class="headline">
            <h1>Nossa missão é mostrar que números também podem ser arte.</h1>
        </section>

        <section class="description">
            <p>O Museu da Matemática é o primeiro museu do Rio de Janeiro dedicado inteiramente ao mundo das ciências exatas e numéricas. Contamos com inúmeras exposições para todas as faixas etárias. Explore o site para conhecer nosso trabalho, faça login para reservar exposições, e venha nos fazer uma visita!</p>
        </section>

        <footer class="footer">

        </footer>
        
    </div>
</body>
</html>

museu_matematica/museu_matematica/templates/museu_matematica/lista-reservas.html
{% load static %}
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Suas Reservas</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
        </head>
    <body>

        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <div class ="hellotext_wrapper">
            <h3 class="hellotext">Olá, {% firstof user.username %}!</h3>
            <h2 class="reservas-text">Lista de reservas</h2>
        </div>

        {% if request.user.is_superuser %}
        <div class="admin-stats">
            Estatísticas de admin:
            <h4>{{ reservas.count }} reservas ativas em todo o site.</h4>
        </div>
        {% endif %}

        <div id="search-add-wrapper">
            <form method="GET" style="display: flex;">
                <input id="dataEntrada" type="text" name="search-area" value="{{search_input}}">
                <input class="button" type="submit" value="Search">
            </form>
            <p>Procure reservas por meio de Datas de Entrada no formato AAAA-MM-DD</p> 
        </div>

        <div class="reserva-items-wrapper">
            {% for reserva in reservas %}
                <div class="reserva-wrapper">
                    <div class ="reserva-descricao">
                        {% if request.user.is_superuser %}
                        <span>{{reserva.user}}: </span>
                        {% endif %}
                        <span>Exposição: </span> {{reserva.exposicao}} |
                        <span>Data de entrada: </span> {{reserva.dataEntrada}} |
                        <span>Data de saída: </span> {{reserva.dataSaida}} |
                        <span>Horário de entrada: </span> {{reserva.horarioEntrada}} |
                        <span>Horário de saída: </span> {{reserva.horarioSaida}}
                    </div>
                    <div class = "reserva-buttons">
                        <a href="{% url 'reserva-editar' pk=reserva.id %}"><i class="material-icons" style="font-size:30px">&#9998;</i></a>
                        <a class="delete-link" href="{% url 'reserva-delete' pk=reserva.id %}">&#10799;</a>
                    </div>
                </div>
            {% empty %}
            <div class="reserva-wrapper">
                <h3>Não há nenhuma reserva efetuada.</h3>
            </div>
                
            {% endfor %}
        </div>
    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/login.html
{% load static %}
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <div class="form-wrapper">
            
        <h2>Login</h2>

            <form action="" method="post">
                {% csrf_token %}
                <table>
                    <form action="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input class="button" type="submit" value="Login">
                    </form>
                </table>
            </form>
            <p>Ainda não pussui uma conta? <a href='{% url "registro" %}'>Criar Conta</a></p>
        </div>
    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/registro.html
{% load static %}
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registro</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <h2>Crie sua conta:</h2>

        <div class="form-wrapper">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Cria usuário">
            </form>
        </div>
    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/reserva-delete.html
{% load static %}   
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Excluir reserva</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
        </head>
    <body>

        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}

        <div class="form-wrapper">
            <form method="post">
                {% csrf_token %}
                <h3>Quer realmente remover sua reserva de {{ reserva.exposicao }}?</h3>
                <input class="delete-button" type="submit" value="Excluir">
            </form>
        </div>
    </body>
    </html>

museu_matematica/museu_matematica/templates/museu_matematica/reservas.html
{% load static %}
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Reservas</title>
        <link rel="stylesheet" href="{% static 'museu-matematica/css/styles.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
        </head>
    <body>

        <!-- header do site -->
        {% include 'museu_matematica/header.html' %}
        
        <h1 style="text-align: center;">Lista de Reservas de Exposicoes Efetuadas</h1>
        
        <div id="nova-reserva">
            <a href="{% url 'reservar' %}">Criar nova reserva</a>
        </div>
        

        <div id="search-add-wrapper">
            <form method="GET" style="display: flex;">
                <input id="dataEntrada" type="text" name="search-area" value="{{search_input}}">
                <input class="button" type="submit" value="Search">
            </form>
            <p>Procure reservas por meio de Datas de Entrada no formato AAAA-MM-DD</p> 
        </div>

        <div class="reserva-items-wrapper">
            {% for reserva in reservas %}
                <div class="reserva-wrapper">
                    <span>Data de entrada: </span> {{reserva.dataEntrada}}
                    <span>Data de saída: </span> {{reserva.dataSaida}}
                    <span>Horário de entrada: </span> {{reserva.horarioEntrada}}
                    <span>Horário de saída: </span> {{reserva.horarioSaida}}
                    <a href="{% url 'museu_matematica:reserva-editar' pk=reserva.id %}"><i class="material-icons" style="font-size:15px">border_color</i></a>
                    <a class="delete-link" href="{% url 'museu_matematica:reserva-deletar' pk=reserva.id %}">&#215;</a>
                </div>
            {% empty %}
            <div class="reserva-wrapper">
                <h3>Não há nenhuma reserva efetuada</h3>
            </div>
                
            {% endfor %}
        </div>
    </body>
    </html>